---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  labels:
    app: voting
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: voting
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: voting:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: voting-env
        - secretRef:
            name: voting-secrets
      terminationGracePeriodSeconds: 180